pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'shimaaesmat/jenkins-app'
        DOCKER_HUB_CRED = 'dockerhub-creds'
        GITHUB_REPO = 'https://github.com/Shimaa-esmat/iVolve-Tasks.git'
        GITHUB_CRED = 'github-token'
        IMAGE_TAG = "${BUILD_NUMBER}"
        APP_PATH = './ArgoCD/lab25'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: "${GITHUB_CRED}", url: "${GITHUB_REPO}"
            }
        }

        stage('Build App') {
            steps {
                sh "cd ${APP_PATH} && mvn clean package -DskipTests"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${DOCKER_HUB_REPO}:${IMAGE_TAG}", "${APP_PATH}")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', "${DOCKER_HUB_CRED}") {
                        dockerImage.push("${IMAGE_TAG}")
                        dockerImage.push("latest")
                    }
                }
            }
        }

	stage('Update Deployment') {
	    steps {
		sh "sed -i 's|image:.*|image: ${DOCKER_HUB_REPO}:${IMAGE_TAG}|' ${APP_PATH}/k8s/deployment.yaml"
		withCredentials([string(credentialsId: "${GITHUB_CRED}", variable: 'GITHUB_TOKEN')]) {
		    sh """
			git config user.email "jenkins@ci.com"
			git config user.name "Jenkins CI"
			git add ${APP_PATH}/k8s/deployment.yaml
			git commit -m "Update image ${IMAGE_TAG}"
			git push https://${GITHUB_TOKEN}@github.com/Shimaa-esmat/iVolve-Tasks.git main
		    """
		}
	    }
	}


    }
}

