pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'docker.io'
        DOCKER_USERNAME = 'shimaaesmat'
        IMAGE_NAME = 'demo-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
        FULL_IMAGE_NAME = "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}"
    }

    stages {
        stage('Load Shared Steps') {
            steps {
                script {
                    runUnitTest = load 'vars/runUnitTest.groovy'
                    buildApp = load 'vars/buildApp.groovy'
                    buildImage = load 'vars/buildImage.groovy'
                    scanImage = load 'vars/scanImage.groovy'
                    pushImage = load 'vars/pushImage.groovy'
                    removeImageLocally = load 'vars/removeImageLocally.groovy'
                    deployOnK8s = load 'vars/deployOnK8s.groovy'
                }
            }
        }

        stage('RunUnitTest') {
            steps { script { runUnitTest() } }
        }
        stage('BuildApp') {
            steps { script { buildApp() } }
        }
        stage('BuildImage') {
            steps { script { buildImage(IMAGE_NAME, IMAGE_TAG, "${DOCKER_REGISTRY}/${DOCKER_USERNAME}") } }
        }
        stage('ScanImage') {
            steps { script { scanImage(FULL_IMAGE_NAME) } }
        }
        stage('PushImage') {
            steps { script { pushImage(FULL_IMAGE_NAME, 'dockerhub-credentials') } }
        }
        stage('RemoveImageLocally') {
            steps { script { removeImageLocally(FULL_IMAGE_NAME) } }
        }
        stage('DeployOnK8s') {
            steps { script { deployOnK8s('default', 'K8s/deployment.yaml', 'kubeconfig-credentials') } }
        }
    }
}
