pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'docker.io'
        DOCKER_USERNAME = 'shimaaesmat'
        IMAGE_NAME = 'demo-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
        FULL_IMAGE_NAME = "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}"
    }

    tools {
        maven 'Maven-3.9'
        jdk 'JDK-17'
    }

    stages {

        stage('RunUnitTest') {
            steps { script { runUnitTest() } }
        }

        stage('BuildApp') {
            steps { script { buildApp() } }
        }

        stage('BuildImage') {
            steps {
                script {
                    buildImage(
                        imageName: IMAGE_NAME,
                        imageTag: IMAGE_TAG,
                        dockerRegistry: "${DOCKER_REGISTRY}/${DOCKER_USERNAME}"
                    )
                }
            }
        }

        stage('ScanImage') {
            steps { script { scanImage(FULL_IMAGE_NAME) } }
        }

        stage('PushImage') {
            steps { script { pushImage(FULL_IMAGE_NAME, 'dockerhub-credentials') } }
        }

        stage('RemoveImageLocally') {
            steps { script { removeImageLocally(FULL_IMAGE_NAME) } }
        }

        stage('DeployOnK8s') {
            steps {
                script {
                    deployOnK8s(
                        namespace: 'default',
                        deploymentFile: 'K8s/deployment.yaml',
                        kubeconfigId: 'kubeconfig-credentials'
                    )
                }
            }
        }
    }
}

